apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-docker-proxy
  labels:
    app: vault-docker-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vault-docker-proxy
  template:
    metadata:
      labels:
        app: vault-docker-proxy
    spec:
      containers:
      - name: vault-docker-proxy
        image: vault-docker-proxy:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PORT
          value: "8080"
        - name: VAULT_ADDR
          valueFrom:
            configMapKeyRef:
              name: vault-docker-proxy-config
              key: vault-addr
        livenessProbe:
          httpGet:
            path: /v2/
            port: http
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /v2/
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        securityContext:
          runAsNonRoot: true
          runAsUser: 65534
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL