services:
  vault:
    image: hashicorp/vault:1.20
    container_name: vault-server
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "dev-root-token"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    command: vault server -dev -dev-listen-address=0.0.0.0:8200
    volumes:
      - ./vault-config:/vault/config
      - ./vault-data:/vault/data
    healthcheck:
      test: ["CMD", "sh", "-c", "export VAULT_ADDR=http://localhost:8200 && vault status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  vault-setup:
    image: hashicorp/vault:1.20
    container_name: vault-setup
    depends_on:
      vault:
        condition: service_healthy
    environment:
      VAULT_ADDR: "http://vault:8200"
      VAULT_TOKEN: "dev-root-token"
    volumes:
      - ./init-vault.sh:/init-vault.sh
    command: sh /init-vault.sh

  vault-docker-proxy:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: vault-docker-proxy
    ports:
      - "8080:8080"
    environment:
      VAULT_ADDR: "http://vault:8200"
      PORT: "8080"
    depends_on:
      vault-setup:
        condition: service_completed_successfully
    restart: unless-stopped

volumes:
  vault-data:
  vault-config: